### ISSUE TITLE
Make ServiceInstance to MessageRoutingInformation mapping configurable

### ISSUE THREAD

**Issue by dhermanns** [AxonFramework/extension-springcloud#8]
### Original Message
Using Consul, the possibility to use the SpringCloudHttpBackupCommandRouter could be error prone and takes additional overhead to determine the supported commands of a serviceInstance.

I think in a lot of cases, filtering a certain serviceInstance by using serviceInstanceFilter on the SpringCloudCommandRouter.Builder should be enough to be sure, that the instance supports all needed Commands.

Proposal: Add a property 

```
useAcceptAllCommandMessageFilter
```

to the SpringCloudCommandRouter.Builder. It sets the AcceptAll CommandMessageFilter to the MessageRoutingInformation.

What do you think?

### Proposed Approach
The gist of the problem, is the way we map a `ServiceInstance` to it's command handling capabilities, the `MessageRoutingInformation`. In essence, that could opt to making the `SpringCloudCommandRouter#getMessageRoutingInformation(ServiceInstance)` method configurable through the builder, instead of a method to override if another implementation is necessary.

The default configured operation would thus use the existing approach, which for the `SpringCloudCommandRouter` means retrieval from the `ServiceInstance#getMetadata` field and for the `SpringCloudHttpBackupCommandRouter` means retrieval by  making a REST call. In your application, you could instead adjust that to directly returning a `MessageRoutingInformation` which accepts all incoming commands.

**Comment by smcvb** [comment]
Thanks for starting an issue for this problem you're running into @dhermanns.

We had some internal discussion here and feel that a more generic solution might be better suited.
The gist of the problem, is the way we map a `ServiceInstance` to it's command handling capabilities, the `MessageRoutingInformation`. In essence, that could opt to making the `SpringCloudCommandRouter#getMessageRoutingInformation(ServiceInstance)` method configurable through the builder, instead of a method to override if another implementation is necessary.

The default configured operation would thus use the existing approach, which for the `SpringCloudCommandRouter` means retrieval from the `ServiceInstance#getMetadata` field and for the `SpringCloudHttpBackupCommandRouter` means retrieval by  making a REST call. In your application, you could instead adjust that to directly returning a `MessageRoutingInformation` which accepts all incoming commands.

I'd argue this would change the effort for this issue somewhat, but we do think this might be better suited for a wider audience. What's your take on this @dhermanns?

**Comment by dhermanns** [comment]
> making the SpringCloudCommandRouter#getMessageRoutingInformation(ServiceInstance) method configurable through the builder, instead of a method to override if another implementation is necessary.

So I would be able to implement my own solution which could simply return "AcceptAll".
That sounds like a flexible idea to me.

**Comment by smcvb** [comment]
Yes, that's indeed what we were thinking of. 
We could even move the suggested approach into an interface, where the framework could provide a couple of implementations. The 'AcceptAll' approach could be just such an implementation to choose from in that case.

**Comment by dhermanns** [comment]
Sounds great. Let me know if I can help or test something...

**Comment by smcvb** [comment]
We'll definitely do that @dhermanns! Would very much like your input in this as soon as it's in place.

**Comment by smcvb** [comment]
Although the exact description of this issue has not been implemented yet, #23 did see the introduction of a solution which simply assumes the the `CommandMessageFilter` to be `AcceptAll` for any instance.
Issue #23 has seen this through the introduction of a dedicated `CapabilityDiscoveryMode`, the `AcceptAllCommandsDiscoveryMode`.
What this does is that when a member's capabilities are updated, they're set to `AcceptAll` regardless of the given `CommandMessageFilter`.

I do think this resolves the problem you are experiencing, right @dhermanns?

Note that this does take a different angle.
Instead of allowing the adjustment of the mapping for a `ServiceInstance` to `CommandMessageFilter`, we simply ensure the `ServiceInstance` changes the info it shares.
The described idea above to provide an interface which implements "what" the `CommandMessageFilter` would still very much be an option to taking this route.

Anyhow, let me know whether you feel this solves your problem @dhermanns.

**Comment by dhermanns** [comment]
Yes - thanks. #23 looks to me like it would solve our issues!

**Comment by smcvb** [comment]
Sweet, happy to hear that! 
I am working on a release of 4.4 as we speak, so you should be able to use the new functionality pretty soon.

Taking the solution of #23 into account, I do think this issue can still be implemented but as said from the same angle currently taken in the `AcceptAllCommandsDiscoveryMode`.
Thus an interface which requires the implementation of a method which takes in a load factor, `ServiceInstance` and `CommandMessageFilter`, mapping to the member capabilities to be stored and shared.

**Comment by smcvb** [comment]
After circling back to this issue to deduce whether I should add it to 4.5, I am beginning to doubt whether it still has merit.
The request to impose a `ServiceInstance` to automatically accept all commands is implemented through the `AcceptAllCommandsDiscoveryMode`.

It's just that the user discovering the `ServiceInstance` would still retrieve the information instead of blatantly assuming it to be `AcceptAll`.
From the `CommandMessageFilter`, we could enforce the `AcceptAllCommandsDiscoveryMode#capabilities(ServiceInstance)` method to return `AcceptAll`, of course.
But that would still leave out the `loadFactor`.

Due to the above, the current provided approach, and the relative silence on this issue, I will be closing it as a "won't fix."

@dhermanns, and others, be sure to comment here if you still feel the extension should provide a solution for this.
We would consider opening it again if interest is still present.

**Comment by dhermanns** [comment]
It would be nice to have some documentation/example code of how to configure an "AcceptAll" ServiceInstance in 4.5.

**Comment by smcvb** [comment]
Sure @dhermanns! The Reference Guide does show that in the `application.properties` sample you can find [here](https://docs.axoniq.io/reference-guide/extensions/spring-cloud#configuring-this-extension). Or, where you looking for a java approach to that too?

**Comment by dhermanns** [comment]
Thanks Steven - that helps!
