### ISSUE TITLE
Spring Cloud Kubernetes produces NullPointerException for ServiceInstance#getMetaData

### ISSUE THREAD

**Issue by mtelewicz** [AxonFramework/extension-springcloud#9]
I'm trying to switch from using Spring Cloud Netflix (Eureka) to Spring Cloud Kubernetes as we are running on OpenShift.  Only problem is that KubernetesRegistration.getMetadata() returns null.  This causes a NullPointerException in SpringCloudCommandRouter.updateMembership() when invoked from SpringCloudHttpBackupCommandRouter.updateMembership().

I should add that I'm using Axon v3.3.5 and Spring Cloud Kubernetes v1.0.1.RELEASE.  Also, when I say that KubernetesRegistration.getMetadata() returns null, I mean it is explicitly returning null.  From their github:

```
public class KubernetesRegistration implements Registration, Closeable {
    .
    .
    .
    @Override
    public Map<String, String> getMetadata() {
        return null;
    }
    .
    .
    .
}
```

Any suggestions here?

**Comment by smcvb** [comment]
Given the fact you're receiving a `NullPointerException` because a Spring Cloud Discovery implementation is returning a `null` for the metadata map to me suggest we should have a null check in the `SpringCloudCommandRouter`. 

Should be fairly simple to add, you're obviously welcome to provide a PR for this.

Additionally, you are right to use the `SpringCloudHttpBackupCommandRouter`. 
The back up implementation of the `SpringCloudCommandRouter` is there to cover scenarios where the chosen Spring Cloud Discovery service *does not* provide handles for the metadata of a Service Instance.

Thanks for filing this issue with us @mtelewicz!

**Comment by mtelewicz** [comment]
I'd be happy to do a PR.  It would be my first on Github and for any open source project.  Since this is a simple change it seems ideal!  For the record, I've used Git internally at my job.  So I'm at least familiar with that.

Since I'm not very familiar with the internals of the Spring Cloud extension, what's the intended behavior here if the local service instance metadata map is null?

```

    @Override
    public void updateMembership(int loadFactor, CommandMessageFilter commandFilter) {
        Map<String, String> localServiceInstanceMetadata = localServiceInstance.getMetadata();
        localServiceInstanceMetadata.put(LOAD_FACTOR, Integer.toString(loadFactor));
        SerializedObject<String> serializedCommandFilter = serializer.serialize(commandFilter, String.class);
        localServiceInstanceMetadata.put(SERIALIZED_COMMAND_FILTER, serializedCommandFilter.getData());
        localServiceInstanceMetadata.put(
                SERIALIZED_COMMAND_FILTER_CLASS_NAME, serializedCommandFilter.getType().getName()
        );

        updateMembershipForServiceInstance(localServiceInstance, atomicConsistentHash)
                .ifPresent(consistentHashChangeListener::onConsistentHashChanged);
}
```
Simply bypass adding the items to the map and skip to invoking updateMembershipForServiceInstance()?
